"""Weekly & monthly report generation in Markdown and JSON."""

from datetime import date
from pathlib import Path

from loguru import logger

from app.models import ParsedProject, RiskAssessment, LLMExplanation, WeeklyReport
from app.config import OUTPUT_DIR


def _find_delayed_milestones(project: ParsedProject, assessment: RiskAssessment) -> list[str]:
    """Extract delayed milestone names."""
    delayed = []
    for m in project.milestones:
        if not m.completed and m.variance_days is not None and m.variance_days < 0:
            delayed.append(f"{m.name} (variance: {m.variance_days:.0f}d)")
    # Also from tasks
    for t in project.tasks:
        if t.phase and t.phase != t.name and t.variance_days is not None and t.variance_days < -2 and t.status.lower() not in ("completed", "done"):
            label = f"{t.name}" if t.name != t.phase else t.phase
            delayed.append(f"{label} (variance: {t.variance_days:.0f}d)")
    return delayed[:5]


def _find_critical_tasks(project: ParsedProject) -> list[str]:
    """Extract critical tasks needing attention."""
    critical = []
    for t in project.tasks:
        if t.critical and t.status.lower() not in ("completed", "done") and t.variance_days is not None and t.variance_days < 0:
            critical.append(f"{t.name} (variance: {t.variance_days:.0f}d)")
    return critical[:5]


def _find_upcoming(project: ParsedProject) -> list[str]:
    """Identify upcoming or in-progress work."""
    upcoming = []
    for t in project.tasks:
        if t.status.lower() == "in progress":
            if t.phase and t.phase != t.name:
                upcoming.append(f"{t.phase}: {t.name} ({t.percent_complete:.0f}%)")
            else:
                upcoming.append(f"{t.name} ({t.percent_complete:.0f}%)")
    return upcoming[:5]


def _find_achievements(project: ParsedProject) -> list[str]:
    """Identify recently completed tasks."""
    done = [t for t in project.tasks if t.status.lower() == "completed" and t.percent_complete >= 100]
    return [f"{t.phase + ': ' if t.phase and t.phase != t.name else ''}{t.name}" for t in done[-5:]]


def build_report(project: ParsedProject, assessment: RiskAssessment, explanation: LLMExplanation) -> WeeklyReport:
    """Assemble a structured weekly report."""
    return WeeklyReport(
        project_name=assessment.project_name or project.name,
        assessment_date=str(project.assessment_date or date.today()),
        overall_status=assessment.rag,
        risk_score=assessment.aggregate_score,
        top_risks=assessment.top_reasons[:5],
        key_achievements=_find_achievements(project),
        delayed_milestones=_find_delayed_milestones(project, assessment),
        critical_tasks=_find_critical_tasks(project),
        upcoming_work=_find_upcoming(project),
        recommendations=explanation.recommendations[:5],
        executive_summary=explanation.summary,
    )


def to_markdown(report: WeeklyReport) -> str:
    """Render a weekly report as Markdown."""
    status_icon = {"Green": "[G]", "Amber": "[A]", "Red": "[R]"}
    icon = status_icon.get(report.overall_status, "[?]")

    lines = [
        f"# Weekly Project Health Report",
        f"",
        f"**Project:** {report.project_name}",
        f"**Assessment Date:** {report.assessment_date}",
        f"**Overall Status:** {icon} {report.overall_status}",
        f"**Risk Score:** {report.risk_score:.0f}/100",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        f"{report.executive_summary}",
        f"",
        f"---",
    ]

    if report.top_risks:
        lines.append("")
        lines.append("## Top Risks")
        for r in report.top_risks:
            lines.append(f"- {r}")

    if report.key_achievements:
        lines.append("")
        lines.append("## Key Achievements")
        for a in report.key_achievements:
            lines.append(f"- {a}")

    if report.delayed_milestones:
        lines.append("")
        lines.append("## Delayed Milestones")
        for m in report.delayed_milestones:
            lines.append(f"- {m}")

    if report.critical_tasks:
        lines.append("")
        lines.append("## Critical Tasks")
        for t in report.critical_tasks:
            lines.append(f"- {t}")

    if report.upcoming_work:
        lines.append("")
        lines.append("## Upcoming Work")
        for w in report.upcoming_work:
            lines.append(f"- {w}")

    if report.recommendations:
        lines.append("")
        lines.append("## Recommendations")
        for r in report.recommendations:
            lines.append(f"- {r}")

    lines.append("")
    lines.append("---")
    lines.append("_Auto-generated by Project Health Agent_")
    lines.append("")
    return "\n".join(lines)


def save_report(report: WeeklyReport, prefix: str = "") -> Path:
    """Save report as Markdown and JSON."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    safe_name = report.project_name.replace(" ", "_").replace("/", "_")[:40]
    date_str = report.assessment_date.replace("-", "")
    base = OUTPUT_DIR / f"{prefix}{safe_name}_{date_str}"

    md_path = base.with_suffix(".md")
    md_path.write_text(to_markdown(report), encoding="utf-8")
    logger.info(f"Markdown report saved: {md_path}")

    json_path = base.with_suffix(".json")
    json_path.write_text(report.model_dump_json(indent=2), encoding="utf-8")
    logger.info(f"JSON report saved: {json_path}")

    return md_path
